// Mock data for admin prototype
const DB = {
  organizations: [
    { id:'foretag', title:'Företag AB', details:'Tillverkningsföretag i Småland', subscriptionTier:'pro' },
    { id:'bolaget', title:'Bolaget HB', details:'Handelsbolag inom logistik', subscriptionTier:'basic' },
    { id:'konsult', title:'Konsult Partner AB', details:'Managementkonsulter', subscriptionTier:'plus' },
  ],
  teams: [
    { id:'alpha', title:'Team Alpha', orgId:'foretag' },
    { id:'beta',  title:'Team Beta',  orgId:'foretag' },
    { id:'stod',  title:'Stödgrupp',  orgId:'foretag' },
    { id:'gamma', title:'Team Gamma', orgId:'bolaget' },
    { id:'utv',   title:'Utveckling', orgId:'konsult' },
    { id:'support',title:'Support',   orgId:'konsult' },
  ],
  users: [
    { id:'u1',  firstName:'Håkan',   lastName:'Farnlöf',    email:'hakan.farnlof@integpartner.com', username:'hakan.f', phone:'070-111 22 33', description:'Systemadministratör', systemRole:'super_admin', registerDate:'2024-01-15', registerStatus:'registered', lastActive:'2026-02-17', orgs:[{orgId:'foretag',isPrimary:true},{orgId:'bolaget',isPrimary:false},{orgId:'konsult',isPrimary:false}], memberships:[{teamId:'alpha',teamRole:'team_leader',joinedDate:'2024-01-15'}], chatRole:'boss' },
    { id:'u2',  firstName:'Lena',    lastName:'Bergström',  email:'lena.bergstrom@integpartner.com', username:'lena.b', phone:'070-222 33 44', description:'Kundansvarig', systemRole:'integ_admin', registerDate:'2025-02-01', registerStatus:'registered', lastActive:'2026-02-16', orgs:[{orgId:'foretag',isPrimary:true},{orgId:'bolaget',isPrimary:false}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-02-01'},{teamId:'gamma',teamRole:'member',joinedDate:'2025-03-01'}], chatRole:'coach' },
    { id:'u3',  firstName:'Anna',    lastName:'Andersson',  email:'anna.andersson@foretag.se', username:'anna.a', phone:'070-333 44 55', description:'', systemRole:'org_admin', registerDate:'2025-03-10', registerStatus:'registered', lastActive:'2026-02-15', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'team_leader',joinedDate:'2025-03-10'},{teamId:'beta',teamRole:'member',joinedDate:'2025-04-01'}], chatRole:'coach' },
    { id:'u4',  firstName:'Magnus',  lastName:'Borg',       email:'magnus.borg@bolaget.se', username:'magnus.b', phone:'', description:'', systemRole:'org_admin', registerDate:'2025-04-01', registerStatus:'registered', lastActive:'2026-02-14', orgs:[{orgId:'bolaget',isPrimary:true}], memberships:[{teamId:'gamma',teamRole:'team_leader',joinedDate:'2025-04-01'}], chatRole:'base' },
    { id:'u5',  firstName:'Erik',    lastName:'Svensson',   email:'erik.svensson@foretag.se', username:'erik.s', phone:'070-444 55 66', description:'', systemRole:null, registerDate:'2025-04-20', registerStatus:'registered', lastActive:'2026-02-13', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'beta',teamRole:'team_leader',joinedDate:'2025-04-20'}], chatRole:'coach' },
    { id:'u6',  firstName:'Maria',   lastName:'Johansson',  email:'maria.johansson@foretag.se', username:'', phone:'070-555 66 77', description:'', systemRole:null, registerDate:'2025-05-01', registerStatus:'registered', lastActive:'2026-02-17', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-05-01'}], chatRole:'base' },
    { id:'u7',  firstName:'Lars',    lastName:'Nilsson',    email:'*****@*****.***', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-05-15', registerStatus:'soft_deleted', lastActive:'2025-11-14', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-05-15'}], chatRole:'base' },
    { id:'u8',  firstName:'Sofia',   lastName:'Berg',       email:'sofia.berg@foretag.se', username:'', phone:'070-666 77 88', description:'', systemRole:null, registerDate:'2025-06-01', registerStatus:'registered', lastActive:'2026-01-30', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'beta',teamRole:'member',joinedDate:'2025-06-01'}], chatRole:'base' },
    { id:'u9',  firstName:'Karl',    lastName:'Lindqvist',  email:'karl.lindqvist@foretag.se', username:'karl.l', phone:'', description:'', systemRole:null, registerDate:'2025-06-15', registerStatus:'registered', lastActive:'2026-02-01', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-06-15'},{teamId:'stod',teamRole:'member',joinedDate:'2025-07-01'}], chatRole:'base' },
    { id:'u10', firstName:'Karin',   lastName:'Holm',       email:'karin.holm@foretag.se', username:'', phone:'070-777 88 99', description:'', systemRole:null, registerDate:'2025-07-01', registerStatus:'registered', lastActive:'2026-02-17', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-07-01'}], chatRole:'base' },
    { id:'u11', firstName:'Peter',   lastName:'Ek',         email:'peter.ek@foretag.se', username:'peter.e', phone:'', description:'', systemRole:null, registerDate:'2026-01-20', registerStatus:'pending', lastActive:'', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'beta',teamRole:'member',joinedDate:'2026-01-20'}], chatRole:'base' },
    { id:'u12', firstName:'Eva',     lastName:'Strand',     email:'eva.strand@foretag.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-08-10', registerStatus:'registered', lastActive:'2026-01-28', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'stod',teamRole:'member',joinedDate:'2025-08-10'}], chatRole:'base' },
    { id:'u13', firstName:'Johan',   lastName:'Lund',       email:'johan.lund@foretag.se', username:'johan.l', phone:'070-888 99 00', description:'', systemRole:null, registerDate:'2025-09-01', registerStatus:'registered', lastActive:'2026-02-04', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'beta',teamRole:'member',joinedDate:'2025-09-01'}], chatRole:'base' },
    { id:'u14', firstName:'Lisa',    lastName:'Dahl',       email:'lisa.dahl@foretag.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-09-15', registerStatus:'registered', lastActive:'2026-02-03', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'alpha',teamRole:'member',joinedDate:'2025-09-15'}], chatRole:'base' },
    { id:'u15', firstName:'Anders',  lastName:'Björk',      email:'anders.bjork@foretag.se', username:'anders.b', phone:'', description:'', systemRole:null, registerDate:'2025-10-01', registerStatus:'registered', lastActive:'2026-02-10', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'stod',teamRole:'team_leader',joinedDate:'2025-10-01'}], chatRole:'base' },
    { id:'u16', firstName:'Camilla', lastName:'Roos',       email:'camilla.roos@foretag.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-10-15', registerStatus:'registered', lastActive:'2026-02-12', orgs:[{orgId:'foretag',isPrimary:true}], memberships:[{teamId:'stod',teamRole:'member',joinedDate:'2025-10-15'}], chatRole:'base' },
    { id:'u17', firstName:'Helena',  lastName:'Falk',       email:'helena.falk@bolaget.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-05-01', registerStatus:'registered', lastActive:'2026-01-29', orgs:[{orgId:'bolaget',isPrimary:true}], memberships:[{teamId:'gamma',teamRole:'member',joinedDate:'2025-05-01'}], chatRole:'base' },
    { id:'u18', firstName:'Oscar',   lastName:'Gren',       email:'oscar.gren@bolaget.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2026-02-01', registerStatus:'pending', lastActive:'', orgs:[{orgId:'bolaget',isPrimary:true}], memberships:[{teamId:'gamma',teamRole:'member',joinedDate:'2026-02-01'}], chatRole:'base' },
    { id:'u19', firstName:'Ida',     lastName:'Ström',      email:'ida.strom@bolaget.se', username:'ida.s', phone:'', description:'', systemRole:null, registerDate:'2025-06-01', registerStatus:'registered', lastActive:'2026-02-05', orgs:[{orgId:'bolaget',isPrimary:true}], memberships:[{teamId:'gamma',teamRole:'member',joinedDate:'2025-06-01'}], chatRole:'base' },
    { id:'u20', firstName:'Viktor',  lastName:'Nord',       email:'viktor.nord@bolaget.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-07-01', registerStatus:'registered', lastActive:'2026-02-08', orgs:[{orgId:'bolaget',isPrimary:true}], memberships:[{teamId:'gamma',teamRole:'member',joinedDate:'2025-07-01'}], chatRole:'base' },
    { id:'u21', firstName:'Nils',    lastName:'Åberg',      email:'nils.aberg@konsult.se', username:'nils.a', phone:'', description:'', systemRole:'org_admin', registerDate:'2025-04-01', registerStatus:'registered', lastActive:'2026-02-11', orgs:[{orgId:'konsult',isPrimary:true}], memberships:[{teamId:'utv',teamRole:'team_leader',joinedDate:'2025-04-01'}], chatRole:'boss' },
    { id:'u22', firstName:'Sara',    lastName:'Kraft',      email:'sara.kraft@konsult.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-05-01', registerStatus:'registered', lastActive:'2026-02-09', orgs:[{orgId:'konsult',isPrimary:true}], memberships:[{teamId:'support',teamRole:'team_leader',joinedDate:'2025-05-01'}], chatRole:'base' },
    { id:'u23', firstName:'David',   lastName:'Palm',       email:'david.palm@konsult.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-06-01', registerStatus:'registered', lastActive:'2026-02-06', orgs:[{orgId:'konsult',isPrimary:true}], memberships:[{teamId:'utv',teamRole:'member',joinedDate:'2025-06-01'}], chatRole:'base' },
    { id:'u24', firstName:'Maja',    lastName:'Ek',         email:'maja.ek@konsult.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2025-07-01', registerStatus:'registered', lastActive:'2026-01-25', orgs:[{orgId:'konsult',isPrimary:true}], memberships:[{teamId:'support',teamRole:'member',joinedDate:'2025-07-01'}], chatRole:'base' },
    { id:'u25', firstName:'Tobias',  lastName:'Vinge',      email:'tobias.vinge@konsult.se', username:'', phone:'', description:'', systemRole:null, registerDate:'2026-02-10', registerStatus:'pending', lastActive:'', orgs:[{orgId:'konsult',isPrimary:true}], memberships:[{teamId:'utv',teamRole:'member',joinedDate:'2026-02-10'}], chatRole:'base' },
  ],
  customizations: [
    { orgId:'foretag', category:'agenda', key:'agenda.title', defaultLabel:'Agenda', customLabel:'' },
    { orgId:'foretag', category:'sections', key:'section.goals', defaultLabel:'Mål & Mätetal', customLabel:'' },
    { orgId:'foretag', category:'sections', key:'section.actions', defaultLabel:'Handlingsplan', customLabel:'Åtgärdslista' },
    { orgId:'foretag', category:'modules', key:'module.ideas', defaultLabel:'Idéer', customLabel:'' },
    { orgId:'foretag', category:'modules', key:'module.documents', defaultLabel:'Dokument', customLabel:'Filer' },
    { orgId:'foretag', category:'modules', key:'module.reflections', defaultLabel:'Reflektioner', customLabel:'' },
    { orgId:'foretag', category:'ui', key:'ui.saveButton', defaultLabel:'Spara', customLabel:'' },
    { orgId:'foretag', category:'ui', key:'ui.cancelButton', defaultLabel:'Avbryt', customLabel:'' },
    { orgId:'foretag', category:'ui', key:'ui.statusLabel', defaultLabel:'Status', customLabel:'' },
    { orgId:'foretag', category:'nav', key:'nav.dashboard', defaultLabel:'Dashboard', customLabel:'' },
    { orgId:'foretag', category:'nav', key:'nav.admin', defaultLabel:'Admin', customLabel:'' },
    { orgId:'foretag', category:'nav', key:'nav.myTeams', defaultLabel:'Mina Team', customLabel:'' },
    { orgId:'bolaget', category:'agenda', key:'agenda.title', defaultLabel:'Agenda', customLabel:'Mötesplan' },
    { orgId:'bolaget', category:'sections', key:'section.goals', defaultLabel:'Mål & Mätetal', customLabel:'' },
    { orgId:'bolaget', category:'sections', key:'section.actions', defaultLabel:'Handlingsplan', customLabel:'' },
    { orgId:'bolaget', category:'modules', key:'module.ideas', defaultLabel:'Idéer', customLabel:'' },
    { orgId:'bolaget', category:'ui', key:'ui.saveButton', defaultLabel:'Spara', customLabel:'' },
    { orgId:'bolaget', category:'nav', key:'nav.dashboard', defaultLabel:'Dashboard', customLabel:'' },
    { orgId:'konsult', category:'agenda', key:'agenda.title', defaultLabel:'Agenda', customLabel:'' },
    { orgId:'konsult', category:'sections', key:'section.goals', defaultLabel:'Mål & Mätetal', customLabel:'KPI:er' },
    { orgId:'konsult', category:'sections', key:'section.actions', defaultLabel:'Handlingsplan', customLabel:'' },
    { orgId:'konsult', category:'modules', key:'module.ideas', defaultLabel:'Idéer', customLabel:'' },
    { orgId:'konsult', category:'ui', key:'ui.saveButton', defaultLabel:'Spara', customLabel:'' },
    { orgId:'konsult', category:'nav', key:'nav.dashboard', defaultLabel:'Dashboard', customLabel:'' },
  ]
};

const CUSTOM_CATEGORIES = {
  agenda: { sv: 'Agenda', en: 'Agenda' },
  sections: { sv: 'Sektioner', en: 'Sections' },
  modules: { sv: 'Moduler', en: 'Modules' },
  ui: { sv: 'UI-etiketter', en: 'UI Labels' },
  nav: { sv: 'Navigering', en: 'Navigation' },
};

const ACTORS = {
  'super-admin':  { userId:'u1',  orgs:['foretag','bolaget','konsult'] },
  'integ-admin':  { userId:'u2',  orgs:['foretag','bolaget'] },
  'org-admin':    { userId:'u3',  orgs:['foretag'] },
  'team-leader':  { userId:'u5',  orgs:['foretag'], teams:['beta'] },
  'user':         { userId:'u6',  orgs:['foretag'] },
};
